### ISSUE TITLE
Fluent Settings Icons

### ISSUE THREAD

**Issue by willbert03** [stickfab/pc-fluenticons#1]
Could you do something like [this](https://mwittrien.github.io/BetterDiscordAddons/Themes/_res/SettingsIcons.css) but using the fluent icons?
I made this mock-up of what it could look like. (the sizing is all wrong etc)
![image](https://user-images.githubusercontent.com/71606954/156892941-669aa9bc-ee52-4595-809b-2142e8b2ff3f.png)

**Comment by stickfab** [comment]
Done, read the [readme](https://github.com/stickfab/pc-fluenticons/blob/main/README.md) to see how to install it
