### ISSUE TITLE
[Bug] Settings icons broken with Latest Discord release

### ISSUE THREAD

**Issue by iblowmymind** [stickfab/pc-fluenticons#17]
Title self-explanatory. https://github.com/CreArts-Community/Settings-Icons/issues/8 seems to be having the same issue as well.

Running Discord Stable 178590 (6d3ed59), Host 1.0.9011 (29584), OpenAsar 40b27dd, Replugged v4.0.0-rc.3

**Comment by D3SOX** [comment]
FYI this is how I resolved it: https://github.com/CreArts-Community/Settings-Icons/pull/9

**Comment by iblowmymind** [comment]
Fixed, thanks!
