### ISSUE TITLE
Settings icon not showing

### ISSUE THREAD

**Issue by Mara-Li** [stickfab/pc-fluenticons#9]
Discord version : Stable 142868 (7835ca6)
BetterDiscord 1.6.3
Windows 11

The settings icons are replaced by a circle with interrogation point.

![image](https://user-images.githubusercontent.com/30244939/185757144-6df9eca7-8291-448c-9a42-4acb1e4c3b41.png)

**Comment by stickfab** [comment]
This issue should have been fixed by now with commit 4b46eecb35595f1e727fb7e0ae2f1606fd72dc3e

**Comment by Tharki-God** [comment]
fixed only for powercord/replugged not bd for some reason

**Comment by Tharki-God** [comment]
Use https://github.com/CreArts-Community/Settings-Icons as base for setting icons as it's up to date

**Comment by stickfab** [comment]
I just pushed commit 0177515095ddfc261b32279a577a1fbd3bcce607 that should fix this, using the new settings icons code.
